### ISSUE TITLE
CrossSection widget

### ISSUE THREAD

**Issue by ericdill** [NSLS-II-HXN/PyXRF#9]
Look at this matplotlib object: https://github.com/Nikea/xray-vision/blob/master/xray_vision/backend/mpl/cross_section_2d.py#L255

Its subclass is used [here] (https://github.com/NSLS-II-SRX/controlsui/blob/mk1/controlsui/model.py#L126)

It is the subclass in Nikea/xray-vision#58

**Comment by licode** [comment]
cs values are included at pyxrf GUI.
